"""
McGill Course Equivalency Scraper  --  v2

Handles the 100-result cap by splitting searches until each one fits.
Captures status (green check / red X / expired) from the icon image.
Handles multi-course equivalencies (PSYC100 AND PSYC101 -> ...).

Safe to stop and restart - finished prefixes are skipped.

Run:  python scrape.py
Then: python clean.py
"""

import csv
import os
import re
import time
from playwright.sync_api import sync_playwright

URL = "https://nimbus-ssl.mcgill.ca/exsa/search/searchEquivalency"
OUT_FILE = "raw.csv"
DONE_FILE = "done.txt"
LOG_FILE = "log.txt"

CAP = 100                  # site refuses to show more than this
DELAY = 2                  # seconds between searches
WAIT = 7000                # ms to wait for results
MAX_DEPTH = 4              # how many digits deep we'll split

# --- resilience settings ---
RETRIES = 4                # attempts per search before giving up on it
BACKOFF = [5, 15, 30, 60]  # seconds to wait between those attempts
NET_WAIT = 30              # seconds to sleep while waiting for a dead
MAX_NET_WAIT = 40          #   network to recover (x this many times = ~20min)

# Outer result rows only - excludes the nested per-cell mini-grids
ROW_SEL = ".z-row:not(.list-in-grid-mcgill):not(.list-in-grid-external)"

STATUS_MAP = {
    "status0": "Not Equivalent",
    "status1": "Equivalent",
    "status2": "Expired",
}

# All 289 McGill subject codes, from the Course Catalogue (2026-2027).
# Generated by subjects.py - do not hand-edit.
SUBJECTS = [
    "AAAA", "ACCT", "AEBI", "AECH", "AEHM", "AEIS", "AEMA", "AEPH",
    "AERO", "AFRI", "AFYR", "AGEC", "AGRI", "ANAE", "ANAT", "ANSC",
    "ANTH", "ARCH", "ARTE", "ARTH", "ASPL", "ATOC", "BASC", "BBME",
    "BIEN", "BINF", "BIOC", "BIOE", "BIOL", "BIOS", "BIOT", "BMDE",
    "BPHY", "BREE", "BTEC", "BUS1", "BUS2", "BUSA", "CACC", "CACF",
    "CAFT", "CANC", "CANS", "CATH", "CBUS", "CCAU", "CCCS", "CCFA",
    "CCFC", "CCLW", "CCMA", "CCOM", "CCPA", "CCTR", "CCTX", "CEC2",
    "CEEN", "CEGL", "CEN2", "CENG", "CENT", "CFIN", "CFRN", "CGM2",
    "CGMG", "CHEE", "CHEM", "CHLC", "CHSS", "CIAM", "CINC", "CIVE",
    "CLAS", "CMDC", "CMIS", "CMPL", "CMR2", "CMRK", "CMS2", "CMSC",
    "COGS", "COMP", "COMS", "CORG", "CPAG", "CPD2", "CPDV", "CPL2",
    "CPRL", "CSCI", "CSNM", "CSPN", "CTPT", "DENT", "DUMY", "EAST",
    "ECON", "ECSE", "EDEA", "EDEC", "EDEE", "EDEM", "EDER", "EDES",
    "EDFC", "EDFE", "EDGC", "EDIN", "EDKP", "EDLE", "EDPC", "EDPD",
    "EDPE", "EDPH", "EDPI", "EDPS", "EDPT", "EDSL", "EDSP", "EDTL",
    "EDUM", "ELEC", "ENGL", "ENTO", "ENVB", "ENVR", "EPIB", "EPSC",
    "ESYS", "EXMD", "EXSU", "FACC", "FAES", "FDSC", "FIGS", "FILM",
    "FINE", "FMED", "FMT4", "FMTP", "FRED", "FREN", "FRPC", "FRSL",
    "FSCI", "GDEU", "GEAC", "GEBI", "GECH", "GECS", "GEEC", "GEEE",
    "GEHS", "GEIN", "GEMA", "GEML", "GEMO", "GEOG", "GEPH", "GEPM",
    "GEPR", "GERM", "GESP", "GPHL", "GSFS", "HGEN", "HISP", "HIST",
    "HPSC", "HSED", "HSEL", "HSSM", "IDFC", "IGFS", "IMED", "INDG",
    "INDR", "INDS", "INFS", "INLG", "INSY", "INTD", "INTG", "IPEA",
    "ISLA", "ITAL", "JWST", "LACS", "LAWG", "LEEL", "LIBA", "LING",
    "LLCU", "LSCI", "MATH", "MDPH", "MDST", "MECH", "MGCR", "MGMT",
    "MGPO", "MGSC", "MHEC", "MICR", "MIME", "MIMM", "MPCO", "MPHE",
    "MPMC", "MPQM", "MRKT", "MSUS", "MUCO", "MUCT", "MUEN", "MUGS",
    "MUGT", "MUHL", "MUIN", "MUIT", "MUJZ", "MUMT", "MUPD", "MUPG",
    "MUPP", "MURG", "MUSP", "MUSR", "MUTH", "NEUR", "NRSC", "NSCI",
    "NUR1", "NUR2", "NUR3", "NUTR", "OBGY", "OCC1", "OCCH", "ONCO",
    "OPTH", "ORGB", "OTOL", "PAED", "PARA", "PATH", "PHAR", "PHGY",
    "PHIL", "PHTH", "PHWR", "PHYS", "PLNT", "POLI", "POTH", "PPHS",
    "PPOL", "PRAC", "PROC", "PRV1", "PRV2", "PRV3", "PRV4", "PRV5",
    "PSYC", "PSYT", "PUB2", "PUB3", "QCST", "QLSC", "RADD", "REDM",
    "RELG", "RETL", "RUSS", "SCSD", "SEAD", "SOCI", "SOIL", "SURG",
    "SWRK", "UQAC", "UQSP", "URBP", "WCOM", "WILD", "WMST", "WOOD",
    "WRIT",
]


def log(msg):
    print(msg)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(msg + "\n")


def load_done():
    if not os.path.exists(DONE_FILE):
        return set()
    with open(DONE_FILE) as f:
        return {l.strip() for l in f if l.strip()}


def mark_done(prefix):
    with open(DONE_FILE, "a") as f:
        f.write(prefix + "\n")


def read_count(page):
    """
    Read 'N record(s) found'. The number may be split across elements
    and uses a dot as thousands separator, e.g. '1.702'.
    Returns int, or -1 if not found.
    """
    text = page.locator("body").inner_text()
    squashed = re.sub(r"\s+", "", text)
    m = re.search(r"([\d.,]+)record\(s\)found", squashed)
    if not m:
        return -1
    digits = re.sub(r"[^\d]", "", m.group(1))
    return int(digits) if digits else -1


def looks_like_network_error(err):
    """True if this exception is a connectivity failure, not a page bug."""
    s = str(err).upper()
    for sig in ("ERR_NETWORK", "ERR_INTERNET", "ERR_NAME_NOT_RESOLVED",
                "ERR_CONNECTION", "ERR_TIMED_OUT", "ERR_IO_SUSPENDED",
                "NET::", "TIMEOUT"):
        if sig in s:
            return True
    return False


def wait_for_network(page):
    """
    Block until the McGill server is reachable again. Called when a
    search fails with a connectivity error, so a wifi blip or a slept
    laptop pauses the scrape instead of blowing holes in the data.
    """
    log("  !! network looks down - pausing until it comes back")
    for i in range(MAX_NET_WAIT):
        time.sleep(NET_WAIT)
        try:
            page.goto(URL, timeout=20000)
            log(f"  .. network back after ~{(i + 1) * NET_WAIT}s, resuming")
            return True
        except Exception:
            log(f"  .. still down ({(i + 1) * NET_WAIT}s waited)")
    log("  !! network never recovered - the subject will retry next run")
    return False


def do_search(page, prefix):
    """
    Run one search, with retries. Returns the record count.
    Raises only if every retry fails for a non-network reason.
    On a network outage it waits for recovery and keeps trying.
    """
    last_err = None
    for attempt in range(RETRIES):
        try:
            page.goto(URL, timeout=30000)
            page.wait_for_timeout(2500)

            boxes = page.get_by_role("textbox")
            for i in range(boxes.count()):
                b = boxes.nth(i)
                try:
                    if b.is_visible() and b.is_enabled() and b.is_editable():
                        b.fill("")
                except Exception:
                    pass

            boxes.nth(0).fill(prefix)
            page.get_by_role("button", name="Search").click()
            page.wait_for_timeout(WAIT)
            return read_count(page)

        except Exception as e:
            last_err = e
            if looks_like_network_error(e):
                # don't burn a retry - wait for the network to return
                wait_for_network(page)
                continue
            # some other hiccup: brief backoff, then retry
            pause = BACKOFF[min(attempt, len(BACKOFF) - 1)]
            log(f"  .. {prefix} attempt {attempt + 1} failed "
                f"({type(e).__name__}), retrying in {pause}s")
            time.sleep(pause)

    # exhausted retries
    raise last_err if last_err else RuntimeError("search failed")


def extract_rows(page, prefix, writer):
    """Pull every outer result row into the CSV."""
    rows = page.locator(ROW_SEL)
    n = rows.count()
    written = 0

    for i in range(n):
        row = rows.nth(i)
        try:
            cells = row.locator("td")
            if cells.count() < 5:
                continue

            texts = []
            for j in range(cells.count()):
                # inner_text skips hidden elements, so the invisible
                # "AND" labels stay out unless they're really shown
                texts.append(cells.nth(j).inner_text().strip())

            # status lives in an <img src=".../statusN.png">
            status = ""
            imgs = row.locator("img[src*='status']")
            if imgs.count() > 0:
                src = imgs.nth(0).get_attribute("src") or ""
                key = re.search(r"(status\d)", src)
                if key:
                    status = STATUS_MAP.get(key.group(1), key.group(1))

            joined = " || ".join(texts)
            if not joined.strip() or "Legend" in joined:
                continue

            writer.writerow([prefix, status, joined] + texts)
            written += 1
        except Exception:
            continue

    return written


def scrape_prefix(page, prefix, writer, done, depth=0):
    """
    Search one prefix. If the site reports more than CAP results,
    split into prefix+0 ... prefix+9 and recurse.
    """
    if prefix in done:
        log(f"  skip {prefix} (already done)")
        return 0

    count = do_search(page, prefix)
    time.sleep(DELAY)

    if count == -1:
        # No "N record(s) found" text. Before trusting this as a genuinely
        # empty subject, confirm the page actually loaded - a half-loaded
        # page during a network wobble also has no count, and we must NOT
        # mark those done (that's how subjects get falsely lost).
        try:
            has_form = page.get_by_role("button", name="Search").count() > 0
            has_noresults = "no record" in page.locator("body").inner_text().lower()
        except Exception:
            has_form, has_noresults = False, False

        if has_noresults or has_form:
            # page loaded fine and genuinely shows nothing
            log(f"  {prefix:10} no records (empty)")
            mark_done(prefix)
        else:
            # page did NOT load properly - do not trust, leave for retry
            log(f"  {prefix:10} UNREADABLE (page not loaded) - will retry")
        return 0

    if count == 0:
        log(f"  {prefix:10} 0 records")
        mark_done(prefix)
        return 0

    if count <= CAP:
        n = extract_rows(page, prefix, writer)
        flag = "" if n == count else f"  <-- MISMATCH got {n}"
        log(f"  {prefix:10} {count:5} records -> wrote {n}{flag}")
        mark_done(prefix)
        return n

    # too many results - split
    if depth >= MAX_DEPTH:
        log(f"  {prefix:10} {count:5} records - TOO DEEP, taking top {CAP}")
        n = extract_rows(page, prefix, writer)
        mark_done(prefix)
        return n

    log(f"  {prefix:10} {count:5} records - splitting")
    total = 0
    for d in "0123456789":
        total += scrape_prefix(page, prefix + d, writer, done, depth + 1)
    return total


def main():
    done = load_done()
    new_file = not os.path.exists(OUT_FILE)
    grand = 0

    with open(OUT_FILE, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if new_file:
            writer.writerow(["prefix", "status", "raw"] +
                            [f"td{i}" for i in range(1, 9)])

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=False)
            page = browser.new_page()

            for subject in SUBJECTS:
                log(f"\n=== {subject} ===")
                try:
                    grand += scrape_prefix(page, subject, writer, done)
                    f.flush()
                except Exception as e:
                    log(f"  ERROR on {subject}: {e}")

            browser.close()

    log(f"\nTOTAL rows written this run: {grand}")
    log(f"Raw data -> {OUT_FILE}   (now run clean.py)")


if __name__ == "__main__":
    main()
